version: "3"

services:
  infinity-autobuilder:
    image: thetonk/infinity-autobuilder:latest
    container_name: infinity-autobuilder
    labels:
      com.centurylinklabs.watchtower.enable : false
    volumes:
      - "/dockerData/infinity-autobuilder/apk:/output"
      - "infinity-data:/data"
    environment:
      TZ: "Europe/Athens"
      REDDIT_API_KEY: "reddit api key"
      REDDIT_USERNAME: "reddit username"
      DISCORD_WEBHOOK: "discord webhook"
      WEBSERVER_URL: "http://example.net/Infinity.apk"
    restart: unless-stopped

  webserver:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - infinity-autobuilder
    ports:
      - 8081:80
    volumes:
      - "/dockerData/infinity-autobuilder/apk:/usr/share/nginx/html"
    
volumes:
  infinity-data:
    name: infinity-autobuilder-data
